# Project information
site_name: "Open Active Management Technology Cloud Toolkit"
site_url: "https://open-amt-cloud-toolkit.github.io/docs/"
repo_url: "https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit"
repo_name: "open-amt-cloud-toolkit/open-amt-cloud-toolkit"
copyright: "Copyright &copy; 2021 Intel Corporation"
site_dir: site/2.25
# Configuration
theme:
  name: "material"
  language: "en"
  logo: "assets/images/logo-white-75px.png"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.top
    - toc.integrate
    - content.code.copy
  custom_dir: ./docs/overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-schemes)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
# Page tree
nav:
  - Home:
    - Overview: index.md
    - Announcements: announcements.md
    - Release Notes: release-notes.md
    - Video Walkthroughs: videos.md
    - License: license.md
    - Get Help:
      - FAQ: Reference/faq.md
      - Troubleshooting: Reference/troubleshooting.md
  - Get Started:
    - Prerequisites: GetStarted/prerequisites.md
    - Set Up: GetStarted/setup.md
    - Configure:
      - Login to Sample Web UI: GetStarted/loginToUI.md
      - Create a CIRA Config: GetStarted/createCIRAConfig.md
      - Create an AMT Profile:
        - Create a Profile with CCM: GetStarted/createProfileCCM.md
        - Create a Profile with ACM: GetStarted/createProfileACM.md
    - Connect:
      - Build & Run RPC: GetStarted/buildRPC.md
      - Manage AMT Device: GetStarted/manageDevice.md
    - Get Help:
      - FAQ: Reference/faq.md
      - Troubleshooting: Reference/troubleshooting.md
  - Deployment:
    - Overview: Deployment/overview.md
    - Upgrade Toolkit Version: Deployment/upgradeVersion.md
    - Centralized Configuration:
      - Enable Consul: Deployment/centralizedConfiguration.md
    - Database:
      - Schema Overview: Deployment/Database/schema.md
      - SQL Database Replacement: Deployment/Database/database.md
      - NoSQL Databases: Deployment/Database/nosql.md
    - Secrets Management:
      - Secrets Store Replacement: Deployment/secrets.md
  - Tutorials:
    - UI Toolkit Redirection Modules: Tutorials/uitoolkitReact.md
    - REST API Call: Tutorials/apiTutorial.md
    - IDE-Redirection (IDER): Tutorials/ideRedirection.md
    - Wireless Activation: Tutorials/createWiFiConfig.md
    - Modify User Authentication: Tutorials/modifyUserAuth.md
    - Localization:
        - Console: Tutorials/Localization/consoleLocalization.md
        - Sample Web UI: Tutorials/Localization/webuiLocalization.md
    - Scaling Tutorials:
      - Overview: Tutorials/Scaling/overview.md
      - Docker Swarm*: Tutorials/Scaling/docker-swarm.md
      - Kubernetes Deployments:
        - Kubernetes (K8S): Tutorials/Scaling/Kubernetes/deployingk8s.md
        - AKS: Tutorials/Scaling/Kubernetes/deployingk8s-aks.md
        - EKS: Tutorials/Scaling/Kubernetes/deployingk8s-eks.md
        - KUMA Service Mesh: Tutorials/Scaling/Kubernetes/service-mesh.md
    - Get Help:
        - FAQ: Reference/faq.md
        - Troubleshooting: Reference/troubleshooting.md
  - Reference:
    - Architecture Overview: Reference/architectureOverview.md
    - AMT Power States: Reference/powerstates.md
    - GUIDs in Intel® AMT: Reference/guids.md
    - Logging: Reference/logging.md
    - Middleware Extensibility: Reference/middlewareExtensibility.md
    - Production Mode Vault: Reference/productionVault.md
    - SSL with Local Postgres: Reference/sslpostgresLocal.md
    - Console (Alpha):
      - Overview: Reference/Console/overview.md
      - Security Information: Reference/Console/securityConsole.md
      - Get Started: 
        - Download and Run: Reference/Console/GetStarted/setup.md
        - Activate a Device: Reference/Console/GetStarted/activateDevice.md
        - Add a Device: Reference/Console/GetStarted/addDevice.md
        - Manage a Device: Reference/Console/GetStarted/manageDevice.md
      - WSMAN Explorer: Reference/Console/wsmanExplorer.md
    - Enterprise Assistant:
      - Overview: Reference/EA/overview.md
      - TLS Certificate Template: Reference/EA/tlsCertTemplate.md
      - RPC-Go Configuration:
        - EA Configuration for RPC-Go: Reference/EA/RPCConfiguration/rpcgoConfiguration.md
        - TLS Configuration: Reference/EA/RPCConfiguration/localtlsconfig.md
        - 802.1x Configuration: Reference/EA/RPCConfiguration/localIEEE8021xConfig.md
      - RPS Configuration:
        - EA Configuration for RPS: Reference/EA/RPSConfiguration/rpsConfiguration.md
        - 802.1x Configuration: Reference/EA/RPSConfiguration/remoteIEEE8021xConfig.md
    - Event Monitoring (MQTT):
      - Customizing MQTT Events: Reference/MQTT/customMqttEvents.md
      - Viewing MQTT Events: Reference/MQTT/viewMqttEvents.md
    - Management Presence Server:
      - Configuration: Reference/MPS/configuration.md
      - Security Information: Reference/MPS/securityMPS.md
    - Remote Provisioning Server:
      - Configuration: Reference/RPS/configuration.md
      - Security Information: Reference/RPS/securityRPS.md
      - Create Profile with TLS: Reference/RPS/createProfileTLSConfig.md
    - Remote Provisioning Client:
      - Build RPC-Go Manually: Reference/RPC/buildRPC_Manual.md
      - RPC CLI: Reference/RPC/commandsRPC.md
      - RPC Library: Reference/RPC/libraryRPC.md
      - Transition Activated Device: Reference/RPC/transitionDeviceRPC.md
    - UI Toolkit React:
      - React Controls:
        - Keyboard, Video, Mouse: Reference/UIToolkit/Controls/kvmControl.md
        - Serial Over LAN: Reference/UIToolkit/Controls/serialOverLANControl.md
      - React Localization: Reference/UIToolkit/reactLocalization.md
      - React Bundles:
        - Keyboard, Video, Mouse: Reference/UIToolkit/Bundles/kvmReact.md
        - Serial Over LAN: Reference/UIToolkit/Bundles/serialOverLANReact.md
      - Webpack Configuration: Reference/UIToolkit/webpackConfig.md
    - Intel&reg; MEBX:
      - DNS Suffix: Reference/MEBX/dnsSuffix.md
      - Unprovisioning: Reference/MEBX/unprovision.md
    - Certificates:
      - Custom Provisioning Certificate: Reference/Certificates/generateProvisioningCert.md
      - Provisioning Certificate: Reference/Certificates/remoteProvisioning.md
      - TLS Certificate: Reference/Certificates/tls.md
    - Get Help:
      - FAQ: Reference/faq.md
      - Troubleshooting: Reference/troubleshooting.md
  - APIs:
    - Management Presence Server: APIs/indexMPS.md
    - Remote Provisioning Server: APIs/indexRPS.md
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/branding.css
  - assets/stylesheets/index.css
  - assets/stylesheets/videos.css

plugins:
  - render_swagger
  - search
  - macros
  - img2fig
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/yrcMp2kDWh
      name: Join Us on Discord
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/search?q=intel%2Foact
      name: Find our Dockerhub Images
    - icon: fontawesome/brands/github 
      link: https://github.com/open-amt-cloud-toolkit
      name: Open AMT Github Repository
  version:
    provider: mike
    default:
      - rapid
      - lts
      - dev
  repoVersion:
    mpsAPI: 2.13.0
    rpsAPI: 2.22.0
    oamtct: 2.25.0
    rpc_go: 2.37.0
    webui: 3.15.0
    rpc_c: 2.0.0
    ui_toolkit: 3.2.8
    ui_toolkit_react: 3.2.8
    ui_toolkit_angular: 8.0.3
  docsSite:
    ltsVersion: 2.0
  analytics:
    provider: google
    property: "G-00QEDJW2TS"
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
